<?php

namespace ContainerPAQcSke;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4msqW43Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4msqW43' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4msqW43'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AddBookController::index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\AddBookController::index()', 'getAddBookControllerindexService', true],
            'App\\Controller\\AddBookController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AddBookController::new()', 'getAddBookControllernewService', true],
            'App\\Controller\\AddBookController::show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\AddBookController::show()', 'getAddBookControllershowService', true],
            'App\\Controller\\AddBookController::edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\AddBookController::edit()', 'getAddBookControllereditService', true],
            'App\\Controller\\AddBookController::delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\AddBookController::delete()', 'getAddBookControllerdeleteService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AddBookController:index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\AddBookController::index()', 'getAddBookControllerindexService', true],
            'App\\Controller\\AddBookController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AddBookController::new()', 'getAddBookControllernewService', true],
            'App\\Controller\\AddBookController:show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\AddBookController::show()', 'getAddBookControllershowService', true],
            'App\\Controller\\AddBookController:edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\AddBookController::edit()', 'getAddBookControllereditService', true],
            'App\\Controller\\AddBookController:delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\AddBookController::delete()', 'getAddBookControllerdeleteService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AddBookController::index' => '?',
            'App\\Controller\\AddBookController::new' => '?',
            'App\\Controller\\AddBookController::show' => '?',
            'App\\Controller\\AddBookController::edit' => '?',
            'App\\Controller\\AddBookController::delete' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AddBookController:index' => '?',
            'App\\Controller\\AddBookController:new' => '?',
            'App\\Controller\\AddBookController:show' => '?',
            'App\\Controller\\AddBookController:edit' => '?',
            'App\\Controller\\AddBookController:delete' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
