version: '3.9'

services:
  php:
    build: ./docker/php
    container_name: library_php
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: library_nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: library_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_system
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:20-alpine
    container_name: library_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev"

volumes:
  db_data:
