services:
  # Symfony / PHP app
  app:
    build: .
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - database

  # MySQL Database
  database:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # phpMyAdmin for database GUI
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8082:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
