<?php

namespace ContainerXnFAuxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBook3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lN0jXOy.App\Entity\Book' shared service.
     *
     * @return \App\Entity\Book
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lN0jXOy": it needs an instance of "App\\Entity\\Book" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
