<?php

namespace ContainerXnFAuxc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNonPaidUserControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cWNy2ov.App\Controller\NonPaidUserController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cWNy2ov.App\\Controller\\NonPaidUserController::edit()'] = ($container->privates['.service_locator.cWNy2ov'] ?? $container->load('get_ServiceLocator_CWNy2ovService'))->withContext('App\\Controller\\NonPaidUserController::edit()', $container);
    }
}
