<?php

namespace ContainerZvqpSAH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddBookControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.52LSSp5.App\Controller\AddBookController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.52LSSp5.App\\Controller\\AddBookController::delete()'] = ($container->privates['.service_locator.52LSSp5'] ?? $container->load('get_ServiceLocator_52LSSp5Service'))->withContext('App\\Controller\\AddBookController::delete()', $container);
    }
}
