<?php

namespace Container5HL7pWM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cu8r3mFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cu8r3mF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cu8r3mF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AddBookController::index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\AddBookController::index()', 'getAddBookControllerindexService', true],
            'App\\Controller\\AddBookController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AddBookController::new()', 'getAddBookControllernewService', true],
            'App\\Controller\\AddBookController::show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\AddBookController::show()', 'getAddBookControllershowService', true],
            'App\\Controller\\AddBookController::edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\AddBookController::edit()', 'getAddBookControllereditService', true],
            'App\\Controller\\AddBookController::delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\AddBookController::delete()', 'getAddBookControllerdeleteService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BorrowController::borrow' => ['privates', '.service_locator.lN0jXOy.App\\Controller\\BorrowController::borrow()', 'getBorrowControllerborrowService', true],
            'App\\Controller\\NonPaidUserController::index' => ['privates', '.service_locator.acMEzFW.App\\Controller\\NonPaidUserController::index()', 'getNonPaidUserControllerindexService', true],
            'App\\Controller\\NonPaidUserController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\NonPaidUserController::new()', 'getNonPaidUserControllernewService', true],
            'App\\Controller\\NonPaidUserController::show' => ['privates', '.service_locator.YrSr42h.App\\Controller\\NonPaidUserController::show()', 'getNonPaidUserControllershowService', true],
            'App\\Controller\\NonPaidUserController::edit' => ['privates', '.service_locator.cWNy2ov.App\\Controller\\NonPaidUserController::edit()', 'getNonPaidUserControllereditService', true],
            'App\\Controller\\NonPaidUserController::delete' => ['privates', '.service_locator.cWNy2ov.App\\Controller\\NonPaidUserController::delete()', 'getNonPaidUserControllerdeleteService', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\ReturnController::return' => ['privates', '.service_locator.UCbXxc7.App\\Controller\\ReturnController::return()', 'getReturnControllerreturnService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::search' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::search()', 'getUserControllersearchService', true],
            'App\\Controller\\UserController::borrowed' => ['privates', '.service_locator.HnzgoC9.App\\Controller\\UserController::borrowed()', 'getUserControllerborrowedService', true],
            'App\\Controller\\UserController1::index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController1::index()', 'getUserController1indexService', true],
            'App\\Controller\\UserController1::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserController1::new()', 'getUserController1newService', true],
            'App\\Controller\\UserController1::show' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\UserController1::show()', 'getUserController1showService', true],
            'App\\Controller\\UserController1::edit' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController1::edit()', 'getUserController1editService', true],
            'App\\Controller\\UserController1::delete' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController1::delete()', 'getUserController1deleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AddBookController:index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\AddBookController::index()', 'getAddBookControllerindexService', true],
            'App\\Controller\\AddBookController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AddBookController::new()', 'getAddBookControllernewService', true],
            'App\\Controller\\AddBookController:show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\AddBookController::show()', 'getAddBookControllershowService', true],
            'App\\Controller\\AddBookController:edit' => ['privates', '.service_locator.52LSSp5.App\\Controller\\AddBookController::edit()', 'getAddBookControllereditService', true],
            'App\\Controller\\AddBookController:delete' => ['privates', '.service_locator.52LSSp5.App\\Controller\\AddBookController::delete()', 'getAddBookControllerdeleteService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BorrowController:borrow' => ['privates', '.service_locator.lN0jXOy.App\\Controller\\BorrowController::borrow()', 'getBorrowControllerborrowService', true],
            'App\\Controller\\NonPaidUserController:index' => ['privates', '.service_locator.acMEzFW.App\\Controller\\NonPaidUserController::index()', 'getNonPaidUserControllerindexService', true],
            'App\\Controller\\NonPaidUserController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\NonPaidUserController::new()', 'getNonPaidUserControllernewService', true],
            'App\\Controller\\NonPaidUserController:show' => ['privates', '.service_locator.YrSr42h.App\\Controller\\NonPaidUserController::show()', 'getNonPaidUserControllershowService', true],
            'App\\Controller\\NonPaidUserController:edit' => ['privates', '.service_locator.cWNy2ov.App\\Controller\\NonPaidUserController::edit()', 'getNonPaidUserControllereditService', true],
            'App\\Controller\\NonPaidUserController:delete' => ['privates', '.service_locator.cWNy2ov.App\\Controller\\NonPaidUserController::delete()', 'getNonPaidUserControllerdeleteService', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\ReturnController:return' => ['privates', '.service_locator.UCbXxc7.App\\Controller\\ReturnController::return()', 'getReturnControllerreturnService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:search' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::search()', 'getUserControllersearchService', true],
            'App\\Controller\\UserController:borrowed' => ['privates', '.service_locator.HnzgoC9.App\\Controller\\UserController::borrowed()', 'getUserControllerborrowedService', true],
            'App\\Controller\\UserController1:index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController1::index()', 'getUserController1indexService', true],
            'App\\Controller\\UserController1:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserController1::new()', 'getUserController1newService', true],
            'App\\Controller\\UserController1:show' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\UserController1::show()', 'getUserController1showService', true],
            'App\\Controller\\UserController1:edit' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController1::edit()', 'getUserController1editService', true],
            'App\\Controller\\UserController1:delete' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\UserController1::delete()', 'getUserController1deleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AddBookController::index' => '?',
            'App\\Controller\\AddBookController::new' => '?',
            'App\\Controller\\AddBookController::show' => '?',
            'App\\Controller\\AddBookController::edit' => '?',
            'App\\Controller\\AddBookController::delete' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BorrowController::borrow' => '?',
            'App\\Controller\\NonPaidUserController::index' => '?',
            'App\\Controller\\NonPaidUserController::new' => '?',
            'App\\Controller\\NonPaidUserController::show' => '?',
            'App\\Controller\\NonPaidUserController::edit' => '?',
            'App\\Controller\\NonPaidUserController::delete' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\ReturnController::return' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::search' => '?',
            'App\\Controller\\UserController::borrowed' => '?',
            'App\\Controller\\UserController1::index' => '?',
            'App\\Controller\\UserController1::new' => '?',
            'App\\Controller\\UserController1::show' => '?',
            'App\\Controller\\UserController1::edit' => '?',
            'App\\Controller\\UserController1::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AddBookController:index' => '?',
            'App\\Controller\\AddBookController:new' => '?',
            'App\\Controller\\AddBookController:show' => '?',
            'App\\Controller\\AddBookController:edit' => '?',
            'App\\Controller\\AddBookController:delete' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BorrowController:borrow' => '?',
            'App\\Controller\\NonPaidUserController:index' => '?',
            'App\\Controller\\NonPaidUserController:new' => '?',
            'App\\Controller\\NonPaidUserController:show' => '?',
            'App\\Controller\\NonPaidUserController:edit' => '?',
            'App\\Controller\\NonPaidUserController:delete' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\ReturnController:return' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:search' => '?',
            'App\\Controller\\UserController:borrowed' => '?',
            'App\\Controller\\UserController1:index' => '?',
            'App\\Controller\\UserController1:new' => '?',
            'App\\Controller\\UserController1:show' => '?',
            'App\\Controller\\UserController1:edit' => '?',
            'App\\Controller\\UserController1:delete' => '?',
        ]);
    }
}
