<?php

namespace Container5HL7pWM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNonPaidUser2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cWNy2ov.App\Entity\NonPaidUser' shared service.
     *
     * @return \App\Entity\NonPaidUser
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cWNy2ov": it needs an instance of "App\\Entity\\NonPaidUser" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
