<?php

namespace Container5HL7pWM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserController1editService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WkfvUVe.App\Controller\UserController1::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WkfvUVe.App\\Controller\\UserController1::edit()'] = ($container->privates['.service_locator.WkfvUVe'] ?? $container->load('get_ServiceLocator_WkfvUVeService'))->withContext('App\\Controller\\UserController1::edit()', $container);
    }
}
