<?php

namespace ContainerVdLkZDq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GpUkw5IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GpUkw5I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GpUkw5I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController::new' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\BookController::edit' => ['privates', '.service_locator.6VUlBFg.App\\Controller\\BookController::edit()', 'getBookControllereditService', true],
            'App\\Controller\\BookController::delete' => ['privates', '.service_locator.6VUlBFg.App\\Controller\\BookController::delete()', 'getBookControllerdeleteService', true],
            'App\\Controller\\BookController::show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\BookController::show()', 'getBookControllershowService', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.ErcxNfJ.App\\Controller\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\BookController:new' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\BookController:edit' => ['privates', '.service_locator.6VUlBFg.App\\Controller\\BookController::edit()', 'getBookControllereditService', true],
            'App\\Controller\\BookController:delete' => ['privates', '.service_locator.6VUlBFg.App\\Controller\\BookController::delete()', 'getBookControllerdeleteService', true],
            'App\\Controller\\BookController:show' => ['privates', '.service_locator.b3R8WOF.App\\Controller\\BookController::show()', 'getBookControllershowService', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::new' => '?',
            'App\\Controller\\BookController::edit' => '?',
            'App\\Controller\\BookController::delete' => '?',
            'App\\Controller\\BookController::show' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:new' => '?',
            'App\\Controller\\BookController:edit' => '?',
            'App\\Controller\\BookController:delete' => '?',
            'App\\Controller\\BookController:show' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
