<?php

namespace ContainerVdLkZDq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6VUlBFg.App\Controller\BookController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6VUlBFg.App\\Controller\\BookController::edit()'] = ($container->privates['.service_locator.6VUlBFg'] ?? $container->load('get_ServiceLocator_6VUlBFgService'))->withContext('App\\Controller\\BookController::edit()', $container);
    }
}
