<?php

namespace ContainerPLevwL8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CWNy2ovService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cWNy2ov' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cWNy2ov'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'nonPaidUser' => ['privates', '.errored..service_locator.cWNy2ov.App\\Entity\\NonPaidUser', NULL, 'Cannot autowire service ".service_locator.cWNy2ov": it needs an instance of "App\\Entity\\NonPaidUser" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'nonPaidUser' => 'App\\Entity\\NonPaidUser',
            'entityManager' => '?',
        ]);
    }
}
