<?php

namespace ContainerPLevwL8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReturnControllerreturnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UCbXxc7.App\Controller\ReturnController::return()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UCbXxc7.App\\Controller\\ReturnController::return()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'borrowRepo' => ['privates', 'App\\Repository\\BookBorrowRepository', 'getBookBorrowRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'bookRepository' => 'App\\Repository\\BookRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'borrowRepo' => 'App\\Repository\\BookBorrowRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\ReturnController::return()', $container);
    }
}
