<?php

namespace ContainerPLevwL8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserShowershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EWAQaZu.App\Controller\UserShower::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EWAQaZu.App\\Controller\\UserShower::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.EWAQaZu.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.EWAQaZu": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'user' => 'App\\Entity\\User',
        ]))->withContext('App\\Controller\\UserShower::show()', $container);
    }
}
