<?php

namespace ContainerCsWMr3h;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBorrowControllerborrowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lN0jXOy.App\Controller\BorrowController::borrow()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lN0jXOy.App\\Controller\\BorrowController::borrow()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.lN0jXOy.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.lN0jXOy": it needs an instance of "App\\Entity\\Book" but this type has been excluded because it\'s a Doctrine entity.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'book' => 'App\\Entity\\Book',
            'userRepository' => 'App\\Repository\\UserRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\BorrowController::borrow()', $container);
    }
}
