<?php

namespace ContainerCsWMr3h;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNonPaidUserControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YrSr42h.App\Controller\NonPaidUserController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YrSr42h.App\\Controller\\NonPaidUserController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'nonPaidUser' => ['privates', '.errored..service_locator.YrSr42h.App\\Entity\\NonPaidUser', NULL, 'Cannot autowire service ".service_locator.YrSr42h": it needs an instance of "App\\Entity\\NonPaidUser" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'nonPaidUser' => 'App\\Entity\\NonPaidUser',
        ]))->withContext('App\\Controller\\NonPaidUserController::show()', $container);
    }
}
