<?php

namespace ContainerCsWMr3h;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserController1borrowedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HnzgoC9.App\Controller\UserController1::borrowed()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HnzgoC9.App\\Controller\\UserController1::borrowed()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'borrowRepo' => ['privates', 'App\\Repository\\BookBorrowRepository', 'getBookBorrowRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'borrowRepo' => 'App\\Repository\\BookBorrowRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\UserController1::borrowed()', $container);
    }
}
