<?php

namespace ContainerYCruZXJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddBookControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b3R8WOF.App\Controller\AddBookController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b3R8WOF.App\\Controller\\AddBookController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.b3R8WOF.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.b3R8WOF": it needs an instance of "App\\Entity\\Book" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'book' => 'App\\Entity\\Book',
        ]))->withContext('App\\Controller\\AddBookController::show()', $container);
    }
}
