<?php

namespace ContainerYCruZXJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNonPaidUserControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.acMEzFW.App\Controller\NonPaidUserController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.acMEzFW.App\\Controller\\NonPaidUserController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'nonPaidUserRepository' => ['privates', 'App\\Repository\\NonPaidUserRepository', 'getNonPaidUserRepositoryService', true],
        ], [
            'nonPaidUserRepository' => 'App\\Repository\\NonPaidUserRepository',
        ]))->withContext('App\\Controller\\NonPaidUserController::index()', $container);
    }
}
