<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKbF0ZMv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKbF0ZMv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKbF0ZMv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKbF0ZMv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKbF0ZMv\App_KernelDevDebugContainer([
    'container.build_hash' => 'KbF0ZMv',
    'container.build_id' => '406cb11a',
    'container.build_time' => 1759190040,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKbF0ZMv');
