<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxRWtxd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxRWtxd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxRWtxd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxRWtxd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxRWtxd\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxRWtxd',
    'container.build_id' => '1a244b65',
    'container.build_time' => 1759189198,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxRWtxd');
