<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5LglzEv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5LglzEv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5LglzEv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5LglzEv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5LglzEv\App_KernelDevDebugContainer([
    'container.build_hash' => '5LglzEv',
    'container.build_id' => '76ef8c79',
    'container.build_time' => 1759184331,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5LglzEv');
