<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_books' => [[], ['_controller' => 'App\\Controller\\BookController::index'], [], [['text', '/books']], [], [], []],
    'app_borrow' => [['title'], ['_controller' => 'App\\Controller\\BorrowController::index'], [], [['variable', '/', '[^/]++', 'title', true], ['text', '/borrow']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_return' => [['title'], ['_controller' => 'App\\Controller\\ReturnController::index'], [], [['variable', '/', '[^/]++', 'title', true], ['text', '/return']], [], [], []],
    'App\Controller\BookController::index' => [[], ['_controller' => 'App\\Controller\\BookController::index'], [], [['text', '/books']], [], [], []],
    'App\Controller\BorrowController::index' => [['title'], ['_controller' => 'App\\Controller\\BorrowController::index'], [], [['variable', '/', '[^/]++', 'title', true], ['text', '/borrow']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\ReturnController::index' => [['title'], ['_controller' => 'App\\Controller\\ReturnController::index'], [], [['variable', '/', '[^/]++', 'title', true], ['text', '/return']], [], [], []],
];
